name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: package.json
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm test
    - run: git config --global user.name "github-actions[bot]"
    - run: git config --global user.email "github-actions[bot]@users.noreply.github.com"
    - run: npm run deploy:docs
